### ISSUE TITLE
[오픈대응] FE 이슈 리스트

### ISSUE THREAD

**Issue by kjkandrea** [sokWebAdmin/sony-store-react#1049]
임직원 몰, ASC 몰 진입 시 IP 체크 로직 확인 건
A.     저희쪽에서 IP 체크하는  API를 개발 해서 드렸는데 현재 해당 API 를 호출하지 않는 거 같습니다.

* [x] @손대중 : dev에서는 동작했던거 확인했었는데 리얼 한번 확인해주세요.

휴면회원 전환 Issue 건
A.     휴면회원 전환이 정상적으로 되지 않고 있습니다.

* [x] @최소현, @배현수, @이현수: api가 post로 변경되었다고 합니다. 테스트가 힘든상황이라 3분 대화방 따로 파셔서 소통 부탁드립니다.

SNS 로그인  à Facebook 로그인 시 발생되는 이슈의 건
* [x]  @최소현 : memberId전달이 안된다고 하는데요. 다른 메일에 내용있으니 확인부탁드려요~
로그인과 연관되는 화면 접속 의 건
A.     로그인 안된 상태로 브라우져에서 주문 상세 URL로 치고 접근 시 그냥 빈 화면으로 보여짐

B.     https://store.sony.co.kr/my-page/order-detail?orderNo=202111051836571120

@김용식 : alert로 접근 불가능한 페이지 라고 띄우고 뒤로가기 처리하겠습니다.

* [x] @김종근 : 출근시 바로 대응해주세요.

SNS 로직 주석 처리 건
A.     앱 심사를 위해 SNS 로직이 들어가 있는 화면에서 주석 처리가 필요하겠습니다.
* [x] @최소현: 차주 월욜 요청오면 sns 버튼 주석처리하고 리얼 배포 해주세요.

B.     월요일 앱 심사 요청 할 예정이고 시간은 유동적입니다.

MAC PC의 Safari 브라우져에서 소니 스토어 페이지 접속 불가의 건

Safari 버전 13.1.2 

사파리 12.0.2  MAC OS : 모하비 10.14.2
* [x] @김종근 : https://app.lambdatest.com/ 여기서 사파리12로 테스트하여 콘솔 보니 t객체에서 addEventListener가 undefined입니다.
코드 보니깐 index.js의 useMediaQuery부분인것 같아요.  하위 호환성 다 맞추는건 현실적으로 불가능 하여서 사파리 14 미만일 경우 하드 코딩해서 change이벤트 뺴버리는게 좋을것 같습니다.

mediaMatch.addEventListener('change', handler); // 이부분이 에러..

**Comment by choisohyun** [comment]
휴면회원 전환 Issue 건
=> 박진수 선임님이 api 호출 수정 중이라고 확인 받았습니다.  

SNS 로그인 à Facebook 로그인 시 발생되는 이슈의 건
=> 페북에서 로그인할 때 에러가 발생해서 설정 문제가 있는지 확인해 보는 중입니다. 

SNS 로직 주석 처리 건
=> 메일 오면 대응할 예정입니다.

**Comment by kjkandrea** [comment]
추가

[ ] 2. develop -> devstore.sony.co.kr, release -> store.sony.co.kr 최종 배포
[ ] 3. 배포 가이드 작성 (git의 README.md에 추가)

**Comment by kjkandrea** [comment]
사파리12 이슈 완료 981d9bd294cee687c87ceed4ccba5872482d2ec9

**Comment by kjkandrea** [comment]
SNS 로그인 à Facebook 로그인 시 발생되는 이슈의 건 => sony facebook develop 계정 이슈로 대응 불가

**Comment by kjkandrea** [comment]
bye bye
