### ISSUE TITLE
[앱] 헤더 앱 메뉴 : QA스캔, 설정, PUSH 알림 메시지함

### ISSUE THREAD

**Issue by kjkandrea** [sokWebAdmin/sony-store-react#354]
<img width="627" alt="스크린샷 2021-10-05 오후 12 04 51" src="https://user-images.githubusercontent.com/32591477/135953709-b28a297a-7b95-4f72-8c73-dc5b6f894169.png">

**Comment by kjkandrea** [comment]
assign @choisohyun

**Comment by kjkandrea** [comment]
assign @kjkandrea

**Comment by kjkandrea** [comment]
@choisohyun https://github.com/sokWebAdmin/sony-store-react/pull/388 푸쉬해놓았고 테스트만 한번해주시고 이상없으면 이 이슈 클로즈해주세요

**Comment by choisohyun** [comment]
@kjkandrea 
안드로이드, 아이폰 정상동작 확인하였습니다~
