### ISSUE TITLE
[QA] 그룹 상품 > 찜

### ISSUE THREAD

**Issue by nanuya** [sokWebAdmin/sony-store-react#736]
## 요구사항
컬러 옵션이 여러개인 그룹코드의 경우, 현재 대표 색상만 [찜] 가능
> 찜하기 클릭 시 옵션 선택한 컬러가 찜 가능하도록 알럿 띄우기 or 다른 방법 제안 요청(선택한 컬러 찜 가능하도록)

## 내용
- 옵션번호 순으로 정렬되는 이슈 수정완료 -> 대표상품을 제일 앞으로 위치 (https://github.com/sokWebAdmin/sony-store-react/pull/737)

- 이슈가 될 만한 내용 공유드립니다 (to @kjkandrea )
 - 여러 개의 옵션을 선택 혹은 대표상품이 아닌 옵션을 선택하여 찜을 할 경우
    - 해당 상품들이 이미 찜이 되어져 있거나 등등 대표상품과 다른 상태를 갖고 있어 찜 버튼을 눌렀을 때 정의가 필요함
    - (위 내용과 연계된 내용) 찜 api 호출 후 반환되는 결과값 중 대표 상품 번호만 찜 상태를 반영하였을 때.. 소비자는 자신이 선택한 옵션이 찜이 되었는지 찜이 취소가 되었는지 알 수 없음

**Comment by kjkandrea** [comment]
<- @jongkeun
